"""add is_reported to transactions

Revision ID: 788539564a6c
Revises: 20260402_0004
Create Date: 2026-04-09 00:37:27.949019
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '788539564a6c'
down_revision = '20260402_0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_reported', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'is_reported')
    # ### end Alembic commands ###
